katniny/Auride

- assets/js/pageLoader.js
makes it easier to add quotes, just append them to the array
this is entirely a code style thing and should have no user-facing effects
> clean up the random quotes thing

- 404.html
- achievements.html
- assets/css/mainSite.css
- auth/katniny.html
- auth/login.html
- contributors.html
- create_theme.html
- download.html
- indev.html
- index.html
- messages.html
- note.html
- notifications.html
- opensource.html
- policies/child-safety.html
- policies/cookies.html
- policies/copyright.html
- policies/guidelines.html
- policies/privacy.html
- policies/terms.html
- settings.html
- suspended.html
- u.html
- updates.html
im not sure if it works under /auth/katniny and /auth/login because i haven't set up firebase yet. also i have no idea where to put it in /auth/register
btw do you have a specific process to make changes to every file? going through one-by-one is tedious asf
> add noscript message

- 404.html
- achievements.html
- contributors.html
- download.html
- indev.html
- index.html
- messages.html
- note.html
- notifications.html
- opensource.html
- policies/child-safety.html
- policies/cookies.html
- policies/copyright.html
- policies/guidelines.html
- policies/privacy.html
- policies/terms.html
- settings.html
- u.html
- updates.html
the github org doesn't really have anything, so i changed the github icon to link to here instead
> change github link

- .github/ISSUE_TEMPLATE/1-bug-report.yml
- .github/ISSUE_TEMPLATE/2-feature-request.yml
makes it easier to file issues on github. this has literally no effect on transsocial itself, just this repo
also it's a pain in the ass to read/write yaml by hand lol, everything about it except multi-line strings just makes me appreciate json more
> Add bug report and feature request issue templates

- settings.html
i dont think there is any other link to /userstudio and this seems like an appripriate place
> add get themes button to the settings

- assets/js/ts_fas_acih.js
seems you did an oopsie when copy-pasting that part
> fix reply button renoting when it shouldn't

- assets/js/ts_fas_acih.js
- updates.html
> implement new lines

- assets/js/ts_fas_acih.js
this luckily hasn't happened yet
> fix notes by unsuspended people who have previously been suspended not showing up

- assets/js/ts_fas_acih.js
cleans up some duplicate code, and makes it more readable
> abstract sending a notification into a function

- assets/js/ts_fas_acih.js
this is very important fixes every bug that ever existed totally
> the silly :3

- assets/css/mainSite.css
- assets/js/ts_fas_acih.js
- settings.html
- updates.html
finally done, after only committing my api key twice
tested exactly once which is good enough :3
> Account deletion

- .github/workflows/static.yml
sed doesnt support multiline regex, but we can just use multiple expressions. 
im not sure how the string interpolation for the environment variables works, i hope thats right.
> github pages workflow should work now

- auth/register.html
i think this sounds alright.
likely gonna do nothing because the kind of people its meant to stop are brain-dead horny losers that either think with their dicks or not at all and probably lost their ability to read from that (miraculously not the ability to write tho), but gotta have hope and all that.
i should restart work on the moderation tools again
> make the no-dating-site disclaimer in the register form even more obvious

- LICENSE
- README.md
im no lawyer but this sounds more legally binding
btw should i add your email to the copyright notice? I usually add mine to properly identify me (emails are better at that than names imo, especially since git already uses them), but its not that common, and i can understand if you dont just want it there in plain text in a github readme.
> license stuff

- assets/js/config.js
- assets/js/escape.js
- assets/js/greeting.js
- assets/js/pageLoader.js
- assets/js/transsocialAccounts.js
this makes them easier to change without much of a hassle when we need to
> add all the big lists to a centralised place

- assets/js/ts_fas_acih.js
- updates.html
...and more places where it should be `addEventListener` instead of `setAttribute`
idk how to use the `this` thing like that (just function argument ig, havent looked into it at all), but that luckily isnt used in combination with format strings here
MASSIVE TODO we have to redo the note rendering to use the id from the ref
fixes #28
> fix critical security issue in the note click handler

- assets/js/ts_fas_acih.js
- updates.html
quoting and bookmarking broke somewhere between this and ff6e488a7a59a1e1c9d5029377a8e0788eb4b7ee, note view is also broken but that happened before that (ill make an issue on that)
fixes #30 #32
> fix more of those

- assets/js/ts_fas_acih.js
simplify testing for outdated browsers
remove useless else statements and simplify some checks
collapse some `.then` to the same line as what theyre associated to
N\A
- You agree that you have tested your changes, and that you are not opening a Pull Request that you're unsure if it works.
- TransSocial is a **commercial** product that Katniny Studios can profit from. Please do not add copyrighted material to your Pull Request, however there are exceptions (e.g. our Spotify integration).
- This includes things such as security vulnerabilities, ways to manipulate data, etc.
> small code style fixes

- assets/css/settingsTabs.css
- assets/js/ts_fas_acih.js
- settings.html
- updates.html
refactor of the note rendering code, separating the core into its own function, as well as making it more approachable to change imo. 
simplify setting preferences and switching settings tabs to deduplicate a lot of code. this isnt really note worthy at all compared to the other thing, so i didnt mention it in the updates. this also totally wouldve been its own pr before this one but i accidentally committed in the wrong order lol
the initial note loading might be slower than before, im not sure if that wasnt just my awful 1am internet. either way i phrased the update message in a way that indicates that performance wasnt on my mind
please do carefully review, im sure there are some silly logic mistakes in there
btw arrow functions are more recent than standard anonymous functions, so ive …
> refactor note rendering and setting preferences

- policies/privacy.html
---
Fixed collet to collect, changed credientials to credentials, added a comma somewhere idk i can't remember, changed account related to account-related, changed e.g. to e.g., (yes, that is correct). Couple of other minor spelling errors.
---
N/A
---
- You agree that you have tested your changes, and that you are not opening a Pull Request that you're unsure if it works.
- TransSocial is a **commercial** product that Katniny Studios can profit from. Please do not add copyrighted material to your Pull Request, however there are exceptions (e.g. our Spotify integration).
- This includes things such as security vulnerabilities, ways to manipulate data, etc.
> Fixed typos in privacy policy

- assets/js/changeBanner.js
- assets/js/changeBio.js
- assets/js/changeDisplayName.js
- assets/js/changePfp.js
- assets/js/changePronouns.js
- assets/js/changeUsername.js
- assets/js/requiredScripts.js
- assets/js/ts_fas_acih.js
- assets/js/utils.js
- assets/js/versioning.js
---
lifted the faIcon function to the global scope and used it in places it previously wasnt
i didnt use it in those big blobs of html because im scared of touching those and would like to remove them at some point
not a noteworthy change
---
N/A
---
> use the faIcon function in more places

- assets/js/ts_fas_acih.js
- assets/js/utils.js
- assets/js/versioning.js
---
I was annoyed by the huge links
---
N/A
---
> Add a function for storage links

- .gitignore
- src/package-lock.json
- src/package.json
- src/patches/@firebase+database-compat+2.1.0.patch
- src/patches/firebase+12.3.0.patch
- src/public/assets/js/firebase.js
- src/public/assets/js/utils.js
- src/tsconfig.json
- src/types/tus.d.ts
Introduce a basic typescript configuration to get autocompletions on external dependencies
> Improve autocomplete

- server/auride/getNoteData.js
- src/assets/css/notes.css
- src/public/assets/js/notes/notes.js
- src/public/assets/js/notes/renderNoteDiv.js
- src/public/assets/js/versioning.js
- src/updates.html
---
Renotes were not showing up on user pages (somehow the code was removed?) and there was code blocking renotes from showing up whether it worked or not (whoopsies). Auride can now render renotes properly.
---
---
- You agree that you have tested your changes, and that you are not opening a Pull Request that you're unsure if it works.
- Auride is a **commercial** product that Katniny Studios can profit from. Please do not add copyrighted material to your Pull Request, however there are exceptions (e.g. our Spotify integration).
- This includes things such as security vulnerabilities, ways to manipulate data, etc.
- Please make sure to read it, we use this as the standard when reviewing contributions, so it's in your best interest to be familiar with it!
- Unsure what this means? Please …
> Fix renotes
